<?php

namespace App\Models\Common;

use LaravelSupports\Models\Resources\Contracts\ResourceableContract;

/**
 * save file example)
 * $model->saveResourceWithFile(UploadFile);
 *
 * @author  dev9163
 * @added   2021/10/06
 * @updated 2021/10/06
 */
class ResourceableModel extends BaseModel implements ResourceableContract
{
    use \App\Models\Traits\ResourceTrait, \LaravelSupports\Models\Resources\Traits\ResourceableTrait, \App\Models\Traits\SaveResourceTrait;

    public function getResourceStorage(): string
    {
        return 'data';
    }

    public function delete()
    {
        if ($this->resource()->exists()) {
            $this->resource->delete();
        }
        return parent::delete(); // TODO: Change the autogenerated stub
    }
}
