<?php

namespace App\Models\Common;

use Illuminate\Support\Str;
use LaravelSupports\Models\Resources\Contracts\ResourceContract;
use LaravelSupports\Models\Resources\Traits\ResourceTrait;

class ResourcesModel extends BaseModel implements ResourceContract
{
    use ResourceTrait;

    protected $table = 'resources';

    public function delete()
    {
        $this->getStorage()->delete($this->getPath());
        return parent::delete(); // TODO: Change the autogenerated stub
    }

    public function getStorageDisk(): string
    {
        return 'data';
    }

    public function getOriginUrl(): string
    {
        return $this->getStorage()->url("$this->path/$this->origin_name");
    }

    protected static function getData(string $path, string $origin, ?string $name = null): array
    {
        $name = $name ?? Str::random(256);
        $extension = Str::of($origin)->afterLast('.')->lower();
        return [
            'origin_name' => $origin,
            'name' => $name,
            'path' => $path,
            'extension' => $extension,
        ];
    }

    /**
     *
     * @param string $path
     * @param string $origin
     * @param string|null $name
     * @return ResourcesModel
     * @author  dev9163
     * @added   2021/09/15
     * @updated 2021/10/06
     */
    public static function createModel(string $path, string $origin, ?string $name = null): ResourcesModel
    {
        return self::create(self::getData($path, $origin, $name));
    }

}
